apiVersion: v0.1
kind: ActionDefinition
metadata:
  id: PublishToTopic-ZF-7Ib
  scope: account/4QPn5zusDQJtnrdaB
spec:
  arguments:
  - name: message
    type: string
    value: Hello from InOrbit. This is a test message.
  confirmation:
    required: true
  description: ''
  group: Other
  label: Publish ROS topic
  lock: false
  type: PublishToTopic
---
apiVersion: v0.1
kind: ActionDefinition
metadata:
  id: RunScript-RJWpbc
  scope: account/4QPn5zusDQJtnrdaB
spec:
  arguments:
  - name: filename
    type: string
    value: test
  - name: place
    type: string
    value: test_inorbit
  confirmation:
    required: false
  description: Test script
  group: Other
  label: Run a user script
  lock: false
  type: RunScript